name: the_news
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dartz: ^0.10.0
  dio: ^4.0.0
  flutter:
    sdk: flutter
  flutter_app_name: ^0.1.1
  flutter_launcher_icons: ^0.9.2
  get_it: ^7.2.0
  injectable: ^1.5.0
  json_annotation: ^4.1.0
  retrofit: ^2.0.1

dev_dependencies:
  build_runner: ^2.1.1
  flutter_test:
    sdk: flutter
  injectable_generator: ^1.5.0
  json_serializable: ^5.0.0
  retrofit_generator: ^2.0.1+1

dependency_overrides:
  meta: ^1.7.0

flutter:
  uses-material-design: true

  assets:
    - assets/images

flutter_app_name:
  name: "TheNews"

scripts: derry.yaml
